name: Bug report
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.

        Please provide as much detail as you can so we can help determine the best solution.
        
        A clearly documented issue helps others experiencing similiar problems find the discussion.
        
        Additionally, it serves as a record of how and why we made certain decisions.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      placeholder: |
        <!--
          What did you do? (Provide reproduction code in next section)

          What did you expect to happen?

          What happened instead?

          Do you have an error stack-trace?

          Use screenshots or videos to communicate the problem.
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        How can we reproduce the issue? When an issue is immediately reproducible, others can start debugging instead of following-up with questions.
      placeholder: |
        <!--
          Provide one of the following:
            1. A code-snippet that reproduces the issue
            2. A reproduction repository that reproduces the issue
            3. A pull request with a failing test-case

          Please remove as much irrelevant code to make it easier for others to read and debug.
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Describe the environment the issue is happening in. This information is used to for reproduction and debugging.
      placeholder: |
        <!--
          Run and paste the output of:
          ```
          npx envinfo --system --npmPackages @square/maker,vue,webpack --binaries
          ```
        -->

        System:
          OS:
          CPU:
          Memory:
          Shell:
        Binaries:
          Node:
          npm:
        npmPackages:
          @square/maker:
          vue:
          webpack:
      render: shell
    validations:
      required: true
  - type: input
    attributes:
      label: Addressed by
      description: |
        When does this need to be addressed by?
      placeholder: eg. Oct 15, 2021
  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: We would love it if you can open a pull request to fix this bug!
      options:
        - label: I’m interested in opening a pull request for this issue.
