name: Feature request
description: Suggest an idea for this project
labels: [feature request, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this feature request.

        Please provide as much detail as you can so we can help determine the best solution.
        
        A clearly documented issue helps others experiencing similiar problems find the discussion.
        
        Additionally, it serves as a record of how and why we made certain decisions.
  - type: textarea
    attributes:
      label: Feature request
      description: A description of the feature you would like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: |
        Describe the problem you’re tackling with this feature request.
      placeholder: |
        <!--
          What’s the motivation behind this issue?

          eg. “I’m frustrated when...”
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Have you considered alternative solutions? Is there a workaround?
      placeholder: |
        <!--
          Do you have alternative proposals?

          Do you have a workaround?
        -->
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Anything else to share? Screenshots? Links?
