name: Request a new component
description: Provide details to help define a new component for the system
labels: [new component request, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ This is a public repository. Please be aware of sensitive information and prefer referencing internal links.**

        Please leverage this template to provide as much details about the visual and functional requirements for this new component. Doing so will help use communicate and collborate on a solution effectively.

  - type: text
    attributes:
      label: Figma link
      description: Provide a Figma link as a reference
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Provide as much detail as possible about the visual and functional requirements.
      placeholder: |
        <!--
          Consider UI/UX like affordance, user interaction, and different states
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: API
      description: |
        Sample code of the component in use. Consider all necessary props, events, and slots. Simple examples are fine.
      placeholder: |
        <!--
          We recommend looking at similar components in Maker (and/or other design systems like Orbit, Material, Carbon) and referencing those if relevant. 
        -->
      validations:
        required: true
  - type: textarea
    attributes:
      label: Theme support
      description: |
        How will Maker theming impact this component?
      placeholder: |
        <!--
          Design elements like color and color contrast, font-families, border radius are customizable in the Theme. Describe how this component may react to a theme.
        -->
