name: Lint Code & Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-test:
    name: Lint Code & Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install NPM dependencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Run Tests
      run: npm run test --if-present
