name: Lint

on:
  push:
    branches: [master, next, next-major, beta, alpha]
  pull_request:
    branches: [master, next, next-major, beta, alpha]

jobs:
  lint-test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      shell: bash -l {0}
      run: |
        nvm i
        npm ci
        npm run lint
        node .github/dep-version-check
