name: Lint Code & Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-test:
    name: Lint Code & Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      shell: bash -l {0}
      run: |
        nvm i
        npm ci
        npm run lint
