# this workflow has been broken for a while
# so we manually disabled it from the Github UI
# we can re-enable it after it is fixed

name: Package size report

on: pull_request

jobs:
  pkg-size-report:
    name: Package size report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package size report
        uses: privatenumber/pkg-size-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          hide-files: '*.{js,css}.map'
